DROP DATABASE IF EXISTS GRUPOYNL;
CREATE DATABASE GRUPOYNL;
USE GRUPOYNL;

CREATE TABLE GRUPOYNL(
    cveGrupo CHAR(4) PRIMARY KEY NOT NULL,
    NL INT(2) NOT NULL
);

INSERT INTO GRUPOYNL VALUES ('AMPG','32');